blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/dongdio/OpenList/discussions
    about: Use GitHub discussions for message-board style questions and discussions.