name: build

on:
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        target:
          - darwin-amd64
          - darwin-arm64
          - windows-amd64
          - linux-arm64-musl
          - linux-amd64-musl
          - windows-arm64
    #          - android-arm64
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Setup web
        run: bash build.sh dev web
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: OpenListTeam/cgo-actions@v1.2.1
        with:
          targets: ${{ matrix.target }}
          musl-target-format: $os-$musl-$arch
          out-dir: build
          x-flags: |
            github.com/dongdio/OpenList/v4/internal/conf.BuiltAt=$built_at
            github.com/dongdio/OpenList/v4/internal/conf.GitAuthor=OpenList
            github.com/dongdio/OpenList/v4/internal/conf.GitCommit=$git_commit
            github.com/dongdio/OpenList/v4/internal/conf.Version=$tag
            github.com/dongdio/OpenList/v4/internal/conf.WebVersion=dev

      - name: Verify build output
        run: |
          echo "=== Build output directory ==="
          ls -la build/
          echo "=== Target file info ==="
          find build -name "openlist*" -type f -exec ls -la {} \;

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openlist_${{ steps.short-sha.outputs.sha }}_${{ matrix.target }}
          path: build/*
          retention-days: 7