name: Release Automatic changelog

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  changelog:
    name: Create Release Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete beta tag if exists
        run: git tag -d beta || echo "Beta tag not found, continuing..."
        continue-on-error: true

      - name: Generate changelog
        id: changelog
        run: |
          echo "Generating changelog for tag: ${{ github.ref_name }}"
          echo "Current branch: $(git branch --show-current)"
          echo "All tags: $(git tag -l)"

      - name: Create/Update changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Verify changelog generation
        run: |
          echo "Changelog generation completed"
          echo "Release URL: https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}"