name: release_linux_musl_arm

on:
  release:
    types: [published]

permissions: write-all

jobs:
  release_linux_musl_arm:
    # 等待主发布工作流完成
    needs: [] # GitHub Actions不支持跨文件的依赖，但可以通过API或其他方式等待
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Linux musl ARM targets
        id: build_linux_musl_arm
        run: |
          # 创建构建日志
          touch linux_musl_arm_build_log.txt

          # 运行构建并捕获输出
          bash build.sh release linux_musl_arm | tee linux_musl_arm_build_log.txt

          # 检查构建是否成功
          if [ $? -ne 0 ]; then
            echo "::error::Linux musl ARM build failed. See log for details."
            exit 1
          fi

          # 确保目录存在
          mkdir -p build/compress

          # 检查构建产物
          echo "=== Linux musl ARM build output ==="
          find build -name "*linux*arm*" -type f | sort

          # 检查压缩文件
          echo "=== Linux musl ARM compress files ==="
          find build/compress -type f | sort

          # 如果compress目录为空，尝试查找并移动文件
          if [ -z "$(ls -A build/compress 2>/dev/null)" ]; then
            echo "::warning::No Linux musl ARM files found in build/compress directory"
            # 尝试查找构建产物并移动
            find build -name "*linux*arm*.zip" -o -name "*linux*arm*.tar.gz" | xargs -I{} cp {} build/compress/ || true
          fi

      - name: Upload Linux musl ARM assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/compress/*
          prerelease: false
          fail_on_unmatched_files: false

      - name: Upload build logs as artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-arm-build-logs
          path: |
            linux_musl_arm_build_log.txt
            build/
          retention-days: 7
