name: release_freebsd

on:
  release:
    types: [ published ]

permissions: write-all

jobs:
  release_freebsd:
    # 等待主发布工作流完成
    needs: [ ] # GitHub Actions不支持跨文件的依赖，但可以通过API或其他方式等待
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build FreeBSD targets
        id: build_freebsd
        run: |
          # 创建构建日志
          touch freebsd_build_log.txt

          # 运行构建并捕获输出
          bash build.sh release freebsd | tee freebsd_build_log.txt

          # 检查构建是否成功
          if [ $? -ne 0 ]; then
            echo "::error::FreeBSD build failed. See log for details."
            exit 1
          fi

          # 确保目录存在
          mkdir -p build/compress

          # 检查构建产物
          echo "=== FreeBSD build output ==="
          find build -name "*freebsd*" -type f | sort

          # 检查压缩文件
          echo "=== FreeBSD compress files ==="
          find build/compress -type f | sort

          # 如果compress目录为空，尝试查找并移动文件
          if [ -z "$(ls -A build/compress 2>/dev/null)" ]; then
            echo "::warning::No FreeBSD files found in build/compress directory"
            # 尝试查找构建产物并移动
            find build -name "*freebsd*.zip" -o -name "*freebsd*.tar.gz" | xargs -I{} cp {} build/compress/ || true
          fi

      - name: Upload FreeBSD assets
        uses: softprops/action-gh-release@v2
        with:
          files: build/compress/*
          prerelease: false
          fail_on_unmatched_files: false

      - name: Upload build logs as artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: freebsd-build-logs
          path: |
            freebsd_build_log.txt
            build/
          retention-days: 7