name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */3 * * *'  # 每 3 小时整点运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/OpenListTeam/OpenList.git
          git fetch upstream

      - name: Check for updates
        id: check
        run: |
          LOCAL=$(git rev-parse HEAD)
          UPSTREAM=$(git rev-parse upstream/main)
          echo "LOCAL=$LOCAL"
          echo "UPSTREAM=$UPSTREAM"
          if [ "$LOCAL" != "$UPSTREAM" ]; then
            echo "needs_sync=true" >> $GITHUB_OUTPUT
          else
            echo "needs_sync=false" >> $GITHUB_OUTPUT
          fi

      - name: Merge if updated
        if: steps.check.outputs.needs_sync == 'true'
        run: |
          git merge upstream/main --allow-unrelated-histories -m "Auto-sync from upstream"

      - name: Push to fork
        if: steps.check.outputs.needs_sync == 'true'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
